[package]
name = "bash-git-status"
version = "0.3.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gix = { version = "0.88", default-features = false, features = [
    "max-performance-safe",
    "revision",
    "sha1",
    "sha256",
    "status",
] }
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
num_enum = "0.7.3"
interprocess = "2"
rustix = { version = "1", features = ["fs", "process"] }
clap = { version = "4", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
] }

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
